CC=gcc
CLFAGS=-m32 -fno-stack-protector -O0 -g


stack_showcase:
	$(CC) stack_showcase.c -o stack_showcase $(CLFAGS)

heap_showcase:
	$(CC) heap_showcase.c -o heap_showcase $(CLFAGS)

.PHONY: stack_showcase heap_showcase
